version: '3'
services:

  carma-simulation:
    privileged: true
    image: usdotfhwastol/carma-simulation:carma-simulation-1.0.1
    networks:
      carma_sim_net:
        ipv4_address: 172.2.0.2
    container_name: carma-simulation
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    command: "./mosaic.sh -s Town04_20"

  roscore_1:
    image: usdotfhwastol/carma-base:carma-system-4.2.0
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.2
    container_name: roscore_1
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/logs:/opt/carma/logs
    restart: always
    environment:
      - ROS_IP=172.3.0.2
      - ROS_MASTER_URI=http://172.3.0.2:11311/
    command: roscore

  platform_1:
    image: usdotfhwastol/carma-platform:carma-system-4.2.0
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.3
    container_name: platform_1
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
      - /opt/carma/yolo:/opt/carma/yolo
      - /opt/carma/maps:/opt/carma/maps
      - /opt/carma/routes:/opt/carma/routes
      - /opt/carma/data:/opt/carma/data
      - /opt/carma/simulation:/opt/carma/simulation
    environment:
      - ROS_IP=172.3.0.3
      - ROS_MASTER_URI=http://172.3.0.2:11311/
    command: bash -c 'wait-for-it.sh 172.3.0.2:11311 -- roslaunch /opt/carma/vehicle/config/carma_docker.launch'

  platform_ros2_1:
    image: usdotfhwastol/carma-platform:carma-system-4.2.0
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.4
    container_name: platform_ros2_1
    volumes_from:
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
      - /opt/carma/maps:/opt/carma/maps
      - /opt/carma/routes:/opt/carma/routes
      - /opt/carma/yolo:/opt/carma/yolo
    command: bash -c 'source /opt/carma/install_ros2/setup.bash && ros2 launch /opt/carma/vehicle/config/carma_docker.launch.py'

  ros1_bridge_1:
    image: usdotfhwastol/carma-msgs:carma-system-4.2.0
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.5
    container_name: ros1_bridge_1
    volumes_from:
      - container:carma-config:ro
    environment:
      - ROS_IP=172.3.0.5
      - ROS_MASTER_URI=http://172.3.0.2:11311/
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/calibration:/opt/carma/vehicle/calibration
      - /opt/carma/maps:/opt/carma/maps
      - /opt/carma/routes:/opt/carma/routes
      - /opt/carma/yolo:/opt/carma/yolo
    command: bash -c 'wait-for-it.sh 172.3.0.2:11311 -- rosparam load /opt/carma/vehicle/config/bridge.yml && source ~/.base-image/workspace/install/setup.bash && ros2 run ros1_bridge dynamic_bridge --multi-threads'

  carma-carla-integration_1:
    image: usdotfhwastol/carma-carla-integration:carma-ros-2-aws-test
    networks:
      carma_net_1:
        ipv4_address: 172.3.0.6
      carma_sim_net:
        ipv4_address: 172.2.0.6
    container_name: carma-carla-integration_1
    volumes_from:
      - container:carma-config:ro
    environment:
      - ROS_IP=172.3.0.6
      - ROS_MASTER_URI=http://172.3.0.2:11311/
    command: bash -c "sleep 10;
                      export PYTHONPATH=$PYTHONPATH:/home/PythonAPI/carla/dist/carla-0.9.10-py3.7-linux-x86_64.egg &&
                      source /home/carma_carla_ws/devel/setup.bash &&
                      roslaunch carma_carla_agent carma_carla_agent.launch role_name:='hero1'
                                                                           town:='Town04'
                                                                           host:='172.2.0.2'
                                                                           spawn_point:='15.4,-90.1,0,0,0,90'
                                                                           selected_route:='Release_test_case_1'
                                                                           selected_plugins:='RouteFollowingPlugin,InLaneCruisingPlugin,StopAndWaitPlugin,Pure Pursuit'
                                                                           speed_Kp:='0.4'
                                                                           speed_Ki:='0.0'
                                                                           speed_Kd:='0.05'
                                                                           accel_Kp:='0.05'
                                                                           accel_Ki:='0.0'
                                                                           accel_Kd:='0.05'
                                                                           init_speed:='5'
                                                                           init_acceleration:='1'
                                                                           init_steering_angle:='0'
                                                                           init_jerk:='0'
                                                                           max_steering_degree:='70'"
  carma-vehicle-nats-bridge_1:
    image: usdotfhwastoldev/carma_vehicle_nats_bridge:develop
    logging:
        options:
          max-size: "10m"
          max-file: "1"
    networks:
        carma_net_1:
          ipv4_address: 172.3.0.7
    container_name: carma_vehicle_bridge_1
    env_file:
      - /opt/carma/vehicle/calibration/telematics/telematics.env
    environment:
      - NATS_IP=${NATS_IP} # This variable needs to be explictly defined before bringing the container up. NATS_IP referes to the IP of the cloud instance running the telematic server.
    command:  bash -c 'source /ws/install/setup.bash && ros2 launch ros2_nats_bridge ros2_nats_bridge_launch.py'

  scenario-runner:
    image: usdotfhwastoldev/carma-scenario-runner:latest
    container_name: carma-scenario-runner
    networks:
      - carma_sim_net
    depends_on:
      - carma-simulation
    entrypoint: >
      bash -c "sleep 30
      && python3 scenario_runner.py
      --scenario MyScenario_1
      --host 172.2.0.2"

networks:
  carma_sim_net:
    ipam:
      config:
        - subnet: 172.2.0.0/16

  carma_net_1:
    ipam:
      config:
        - subnet: 172.3.0.0/16
