# Set the default ros output level
ros=WARN
roscpp.superdebug=WARN

# Set package specific log level
# Syntax is < my package name>=< Log level>
# Log levels
# DEBUG	Detailed logs useful for debugging
# INFO	Useful logs for understanding system events
# WARN	Warning notifications that represent problems but will not severly degrade system operation
# ERROR	Error notifications that severly degrade system operation, but the system might still be able to operate
# FATAL	Error notification that the system cannot recover from
mpc_follower=WARN
as=WARN
waypoint_generator=WARN
route=WARN
mpc_follower_wrapper=WARN
carma_wm=WARN
arbitrator=WARN
trajectory_executor=WARN
plan_delegator=WARN
inlanecruising_plugin=WARN
route_following_plugin=WARN
pure_pursuit_wrapper=WARN
system_controller=WARN
subsystem_controllers=WARN
