# Set the default ros output level
ros=WARN
roscpp.superdebug=WARN

# Set package specific log level
# Syntax is < my package name>=< Log level>
# Log levels
# DEBUG	Detailed logs useful for debugging
# INFO	Useful logs for understanding system events
# WARN	Warning notifications that represent problems but will not severly degrade system operation
# ERROR	Error notifications that severly degrade system operation, but the system might still be able to operate
# FATAL	Error notification that the system cannot recover from
mpc_follower=INFO
as=WARN
waypoint_generator=INFO
route=INFO
mpc_follower_wrapper=INFO
carma_wm=INFO
arbitrator=WARN
trajectory_executor=INFO
plan_delegator=WARN
inlanecruising_plugin=INFO
route_following_plugin=INFO
pure_pursuit_wrapper=INFO
system_controller=INFO
subsystem_controllers=INFO