# This file allows easier configurations and overrides for individual nodes in carma-platform
# Package and node structure example is provided as a commented out code
# Any parameters here will override the default parameters in the respective package's yaml files
# For brevity the parameter descriptions are not provided here. The descriptions are located
# in each package's parameters yaml file
# Only the parameters that need to be overridden should be included in this file, rest will
# use the default values in the respective package's yaml files
# NOTE: Be sure to include the node name here, which may not be same as the package name
# NOTE: SubsystemControllers has its own override file for easier organization
localization:
  localization_manager:
    ros__parameters:
      localization_mode: 5
      x_offset: 1.8
      y_offset: -2.1

# Nested namespace example for guidance and plugins
guidance:
  plan_delegator:
    ros__parameters:
      max_traj_generation_reattempt: 1000
  plugins:
    yield_plugin:
      ros__parameters:
        intervehicle_collision_distance_in_m: 12.0    # Make collision detection reliable
        time_horizon_until_collision_to_commit_to_stop_in_s: 5.0 # Commits to stopping longer before changing mind
        minimum_safety_gap_in_meters: 13.0  # Try to stop more far away from pedestrian
    lci_strategic_plugin:
      ros__parameters:
        stopping_location_buffer: 7.0
        green_light_time_buffer : 1.0
        desired_distance_to_stop_buffer : 15.0
    inlanecruising_plugin:
      ros__parameters:
        trajectory_time_length: 12.0

environment:
  cp_sdsm_to_detection_list_node:
    ros__parameters:
      adjust_pose: True
      y_offset: -2.0  # Currently, it is to account for poor FLIR camera calibration 08/27/2026
  cp_multiple_object_tracker_node:
    ros__parameters:
      track_removal_threshold: 20 # Some RSU known to lose 1.5s data worst case scenario

# System controller doesn't have a namespace like others
system_controller:
  ros__parameters:
    signal_configure_delay: 10.0
    service_timeout_ms: 500000
    call_timeout_ms: 100000
