#!/bin/bash

if [[ "$SOURCE_BRANCH" = "develop" ]]; then
    # change docker-compose.yml to point to usdotfhwastoldev images
    sed -i "s|usdotfhwastol/|usdotfhwastoldev/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:develop|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:develop|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:develop|g; s|:latest|:candidate|g;" \
     docker-compose.yml
    sed -i "s|usdotfhwastol/|usdotfhwastoldev/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:develop|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:develop|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:develop|g; s|:latest|:candidate|g;" \
     docker-compose-background.yml
elif [[ "$SOURCE_BRANCH" =~ ^release/.*$ ]]; then
    # swap docker-compose.yml and docker-compose-background.yml to point to release images
    RELEASE_NAME=$(echo $SOURCE_BRANCH | cut -d "/" -f 2)
    sed -i "s|usdotfhwastol/|usdotfhwastolcandidate/|g; s|usdotfhwastoldev/|usdotfhwastolcandidate/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:latest|:$RELEASE_NAME|g;" \
     docker-compose.yml
    sed -i "s|usdotfhwastol/|usdotfhwastolcandidate/|g; s|usdotfhwastoldev/|usdotfhwastolcandidate/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:latest|:$RELEASE_NAME|g;" \
     docker-compose-background.yml
fi