#!/bin/bash

if [[ "$SOURCE_BRANCH" = "develop" ]]; then
    # change docker-compose.yml to point to usdotfhwastoldev images
    sed -i "s|usdotfhwastol/|usdotfhwastoldev/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:foxy-develop|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:foxy-develop|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:foxy-develop|g; s|:latest|:candidate|g;" \
     docker-compose.yml
    sed -i "s|usdotfhwastol/|usdotfhwastoldev/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:foxy-develop|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:foxy-develop|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:foxy-develop|g; s|:latest|:candidate|g;" \
     docker-compose-background.yml
elif [[ "$SOURCE_BRANCH" =~ ^release/.*$ ]]; then
    # swap checkout branch in checkout.bash to release branch
    RELEASE_NAME=$(echo $SOURCE_BRANCH | cut -d "/" -f 2)
    sed -i "s|usdotfhwastol/|usdotfhwastolcandidate/|g; s|usdotfhwastoldev/|usdotfhwastolcandidate/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:CARMA[a-zA-Z]*_[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:carma-[a-zA-Z]*-[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:foxy-develop|:$RELEASE_NAME|g" \
     docker-compose.yml
    sed -i "s|usdotfhwastol/|usdotfhwastolcandidate/|g; s|usdotfhwastoldev/|usdotfhwastolcandidate/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:CARMA[a-zA-Z]*_[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:carma-[a-zA-Z]*-[0-9]*\.[0-9]*\.[0-9]*|:$RELEASE_NAME|g; s|:foxy-develop|:$RELEASE_NAME|g" \
     docker-compose-background.yml
fi
