#!/bin/bash

if [[ "$SOURCE_BRANCH" = "develop" ]]; then
    # change docker-compose.yml to point to usdotfhwastoldev images
    sed -i "s|usdotfhwastol|usdotfhwastoldev|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:develop|g; s|:latest|:develop|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:develop|g;" \
     docker-compose.yml
fi