[Settings]
closure_uptrack:5
closure_downtrack:5
target_id:target1
min_gap:5
; Typically advisory_speed_limit is expected mph, but currently set as m/s
; due to an issue 4.10.0 had, which is fixed in 4.11.0.
advisory_speed_limit:2.235
stop_route:stop1
stop_pos:90
start_lane:10_1
stop_lane:0
stop_dist_msger:70
park_area_id:pa_2
