# Autoware transform params
# TODO: Resolve code duplication, this information is already in the base_link -> velodyne TF
tf_x: 0.939
tf_y: 0.0
tf_z: 2.23
tf_yaw: 0.0
tf_pitch: 0.0
tf_roll: -0.0436332
localizer: velodyne
