#!/bin/bash

if [[ "$SOURCE_BRANCH" = "noetic/develop" ]]; then
    # change docker-compose.yml to point to usdotfhwastoldev images
    sed -i "s|usdotfhwastol/|usdotfhwastoldev/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:noetic-develop|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:noetic-develop|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:noetic-develop|g; s|:latest|:candidate|g;" \
     docker-compose.yml
    sed -i "s|usdotfhwastol/|usdotfhwastoldev/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:noetic-develop|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:noetic-develop|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:noetic-develop|g; s|:latest|:candidate|g;" \
     docker-compose-background.yml
elif [[ "$SOURCE_BRANCH" =~ ^release/.*$ ]]; then
    # swap checkout branch in checkout.bash to release branch
    sed -i "s|usdotfhwastol/|usdotfhwastolcandidate/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:candidate|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:candidate|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:candidate|g; s|:latest|:candidate|g;" \
     docker-compose.yml
    sed -i "s|usdotfhwastol/|usdotfhwastolcandidate/|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:candidate|g; s|:CARMASystem_[0-9]*\.[0-9]*\.[0-9]*|:candidate|g; s|:carma-system_[0-9]*\.[0-9]*\.[0-9]*|:candidate|g; s|:latest|:candidate|g;" \
     docker-compose-background.yml
fi