#!/bin/bash
# Script to stop simulation.
# Pulls RTF data from MOSAIC in cdasim container (simulation speed evaluation)
# Stops and removes all docker containers
if ! [ -f /opt/carma-simulation/scripts/extract_rtf_data ] ; then
  echo "Installing extract_rtf_data into /opt/carma-simulation/scripts/ ...."
  wget -q https://raw.githubusercontent.com/usdot-fhwa-stol/carma-analytics-fotda/master/vru_use_case_scripts/extract_rtf_data -P /opt/carma-simulation/scripts
  sudo chmod 777 /opt/carma-simulation/scripts/extract_rtf_data
fi
filename_rtf=cdasim_rtf_data_"$(date +%F_%H-%M-%S)"
echo "Collecting RTF data into ${filename_rtf}.csv"
docker logs carma-simulation 2>&1 |  /opt/carma-simulation/scripts/extract_rtf_data > ${filename_rtf}.csv
echo "Stopping simulation ..."
carma stop all
