name: DockerHub

on:
  push:
    branches:
      - "release/k900-xil"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v3
        with:
          context: ./xil_cloud
          push: true
          tags: usdotfhwastolcandidate/${{ github.event.repository.name }}:k900-xil
